---
- name: "Create Backend Directory"
  become: true
  file:
    path: /home/ubuntu/backend
    state: directory

- name: "Copy and Extract Backend"
  become: true
  unarchive:
    src: artifact.tar.gz
    dest: /home/ubuntu/backend

- name: Start server
  become: true
  shell: |
    cd /home/ubuntu/backend
    npm install
    pm2 stop default
    pm2 start npm -- start

